#!/usr/bin/env bash
# This script tells the story of each user in the /etc/passwd file

# Set IFS to colon (:) to split the fields in /etc/passwd
IFS=:

# Read the file line by line
while read -r username password userid groupid info homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
